### ISSUE TITLE
Feature Request: Set a bookmark folder as the queue repository

### ISSUE THREAD

**Issue by shodanx2** [Holllo/queue#2]
I don't know where queue currently stores the added bookmarks.
But I would like to choose a bookmark folder and have all added bookmarks added to this folder
Then pressing the queue button would move the bookmark out of this folder and out of the queue 
Possibly, bookmarks taken out could be moved to  
"queue bookmark folder/done/" subfolder

**Comment by Bauke** [comment]
The links are stored in Queue's dedicated WebExtension storage. The main idea behind Queue is to not use bookmarks at all for short-lived links, having it work with bookmarks is a bit counter-productive to that end.

**Comment by Bauke** [comment]
Just saw there is a "close as not planned" button on GitHub, so I'll do that instead. (^:
