### ISSUE TITLE
Feature Request: Multiple queues, named queues

### ISSUE THREAD

**Issue by shodanx2** [Holllo/queue#3]
Ability to have more than one queue button
Ability to change color of queue button
Ability to give descriptive name to the queue
When adding a tab to the queue, ability to choose one of the named queue as the destination

If queue is able to use bookmark folders as bookmark storage, ability to have different bookmark folders per named queue

**Comment by Bauke** [comment]
On the one hand I could see this being useful for sorting and categorizing, but on the other hand I feel that if you're saving a considerable amount of links to the point where you need sorting and categorizing options, I think it may be time to look for more complete solutions like [Pinboard](https://pinboard.in/) or simply browser bookmarks.

Queue is all about keeping it very simple and light, and I think multiple queues strays too far from that from both a developer and user side of things.
